extensionsOIDC:
  keycloakUrl: https://sec.dpm.sdlc.app.cbrands.com/auth/"
  # Recommended to utilize this realm primarily for enabling unique integrations and
  # inheriting these capabilities into other realms.
  broker:
    # Create the broker realm with corresponding resources.
    create: true
    # If broker create parameter set to false operator create only a client for connection as Identity Provider,
    # in this case be sure you define correct Realm name.
    name: "broker"

  # If you already have pre-configured realm and don't need to create a new one, set the broker create
  # parameter to false and uncomment existingBroker parameter and provide the name of the existing realm:

  # existingBroker: ""

  # Realm creating for connecting and managing shared services clients, such as Nexus, Sonar, DefectDojo, etc.
  sharedService: "shared"

# ClusterReconciliationEnabled is enabled (set to true), the operator will reconcile all.
# keycloak-operator objects throughout the cluster.
keycloak-operator:
  clusterReconciliationEnabled: true

# Configure components of the External Secrets Operator (ESO).
eso:
  # -- Install components of the ESO.
  enabled: true
  # -- Defines provider type. One of `aws` or `generic`.
  type: "aws"
  # -- Defines Secret Store name.
  secretStoreName: "aws-parameterstore-oidc"
  # -- Value name in AWS ParameterStore, AWS SecretsManager or other Secret Store.
  secretName: "/edp/eks/addons/extensionsOIDC"
  # Defines Secret Store configuration. Used when eso.type is set to "generic".
  generic:
    secretStore:
      # -- Defines SecretStore provider configuration.
      providerConfig: {}
      #  gcpsm:
      #    projectID: "alphabet-123"
